version: 2.1

orbs:
  node: cloudify/public-unittest-orb@1.0.2 #orb version
  releaseorb: cloudify/release-orb@1.0.6 #orb version

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi


executors:

  py36:
    docker:
      - image: circleci/python:3.6

commands:
  release_plugin:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Set Python
          command: |
            if ! pyenv -v COMMAND &> /dev/null
            then
                echo "pyenv could not be found"
                exit
            else
                pyenv global 3.6.5
            fi
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub pyyaml==3.10
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: ecosystem-tests package-release --name cloudify-utilities-plugin-sdk


jobs:

workflows:
  version: 2
  tests:
    jobs: &all_jobs
      - node/check_py3_compat_job
      - node/unittests_job
      - releaseorb/release:
          filters:
            branches:
              only: /master/
          requires:
            - node/unittests_job
  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * *"
        filters:
          branches:
            only:
              - master
    jobs: *all_jobs
