version: 2.1

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  node: cloudify/public-unittest-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  py36:
    docker:
      - image: circleci/python:3.6

  unittesting_docker:
    machine:
      image: ubuntu-2004:202201-02

jobs:

  unittesting:
    executor: unittesting_docker
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: |
          git clone https://github.com/EarthmanT/dockerfiles.git
          docker build -t unittesting dockerfiles/unittesting/
          docker run -e GH_TOKEN=$GITHUB_TOKEN -v $PWD/:/project unittesting

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - unittesting:
          context: 
            - slack-secrets
          <<: *unittest-post-steps

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * *"
        filters:
          branches:
            only:
              - main
    jobs:
      - node/check_py3_compat_job
      - unittesting:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
