version: 2.1

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  node: cloudify/public-unittest-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi


executors:

  py36:
    docker:
      - image: circleci/python:3.6

commands:
  release_plugin:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Set Python
          command: |
            if ! pyenv -v COMMAND &> /dev/null
            then
                echo "pyenv could not be found"
                exit
            else
                pyenv global 3.6.5
            fi
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub pyyaml==3.10
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: ecosystem-tests package-release --name cloudify-utilities-plugin-sdk

  release_sdk_to_pypi:
    steps:
      - run:
          name: "Trigger upload to pypi job"
          command: |
           curl $JENKINS_URL \
           --user $JENKINS_USER:$JENKINS_TOKEN \
           --data BRANCH=master \
           --data GITHUB_PROJECT_URL=$GH_REPO

jobs:

  release_sdk_to_pypi:
    executor: py36
    steps:
      - release_sdk_to_pypi

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
      - releaseorb/release:
          filters:
            branches:
              only: /master/
          requires:
            - node/unittests_job
      - release_sdk_to_pypi:
          context:
            - cloudify-utilities-plugins-sdk
          filters:
            branches:
              only: /master/
          requires:
            - node/unittests_job
  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
