version: 2.1

job-post-steps: &job-post-steps
  post-steps:
   - slack/notify_failed

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  ne: plugins/nativeedge-plugins-orb@0.0.14
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

workflows:
  version: 2.1
  tests:
    jobs:
      - ne/unittests_job:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
      - ne/release:
          filters:
            branches:
              only: main
          requires:
            - ne/unittests_job

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,2,4,6"
        filters:
          branches:
            only:
              - main
    jobs:
      - ne/unittests_job:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
