# Add your custom exclusions
[allowlist]
description = "Repo level allow lists"
paths = [
    '''.*?/tests/.*?''',
    '''nativeedge_kubernetes_sdk/connection/utils.py''',
    '''nativeedge_common_sdk/constants.py''',
]